### ISSUE TITLE
Questions when running console client

### ISSUE THREAD

**Issue by ghost** [chainspace/chainspace-prototype#46]
Hi, this is Amy and I had some issues for this project. 
I followed the instructions from the INSTALL.md to start the console client and it gave me the error: could not find or load main class.

Do you have any thoughts about how to make it work? 

Also could you tell me how to have the result figures from the chainspacemeasurements folder? 

best regards,
Amy

**Comment by musalbas** [comment]
Did you run the command to start the console client while you were in the right directory (/chainspace/chainspacecore)?

**Comment by ghost** [comment]
Thank you for the response. I've solved the first problem. 
I'm trying to run tester.py within the chainspacemeasurements folder. However it gave me the error:

python tester.py clientlatency 1 3 20 20 test
No matching processes were found
No matching processes belonging to you were found
Running client latency measurements for batch size 1 (run 0).
Traceback (most recent call last):
  File "tester.py", line 348, in <module>
    print t.measure_client_latency(min_batch, max_batch, batch_step, runs)
  File "tester.py", line 68, in measure_client_latency
    self.network.config_core(2, 4)
  File "/Users/natlie/PycharmProjects/chainspace-prototype/chainspacemeasurements/instances.py", line 250, in config_core
    shuffled_instances = random.sample(instances, shards * nodes_per_shard)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 325, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

I can't wrap my head around.

Sincerely,
Amy

**Comment by musalbas** [comment]
The clientlatency measurement requires tcpdump to be installed.

**Comment by ghost** [comment]
Hi @musalbas ,
Thanks again for your quick response. I have checked that tcpdump is installed.
So I ran it again:

(venv) AppledeMacBook-Pro-6:chainspace-prototype natlie$ python tester.py clientlatency 20 200 20 5 test123
Password:
No matching processes were found
Running client latency measurements for batch size 20 (run 0).
instances get running instances:0
length of instances: 0
Traceback (most recent call last):
  File "tester.py", line 348, in <module>
    print t.measure_client_latency(min_batch, max_batch, batch_step, runs)
  File "tester.py", line 68, in measure_client_latency
    self.network.config_core(2, 4)
  File "/Users/natlie/PycharmProjects/chainspace-prototype/chainspacemeasurements/instances.py", line 259, in config_core
    raise ValueError("Number of total nodes exceeds the number of running instances.")
ValueError: Number of total nodes exceeds the number of running instances.

The error says that the Number of total nodes exceeds the number of running instances and I find out that the running instances is 0.

Could you tell me how to fix it? 

Best,
Amy

**Comment by musalbas** [comment]
The measurements module uses the Amazon AWS API to create and manage nodes, 
so that's something you'll need to setup, and see instances.py for 
functions that setup the nodes that you can call.

**Comment by ghost** [comment]
Thanks for your explanation, no wonder I can't set this up lol, I will try to understand how AWS works.
Also, Is there any ways to run the local test? I'd like to see how it works before deploying on AWS.

Yours truly,
Amy

**Comment by musalbas** [comment]
Not that I know of, the measurement scripts are coded for AWS.
